### ISSUE TITLE
Installation errors?

### ISSUE THREAD

**Issue by micheledallatorre** [permeance/liferay-webcontent-workflow-portlet#6] opened 2015-09-09 08:54 UTC
Hello,
I installed your plugin on _Liferay Portal Enterprise Edition 6.1.30 EE (Paton / Build 6130 / August 16, 2013)_.

However, checking the documentation (cfr. https://portal.permeance.com.au/liferay-web-content-workflow-configuration), I noticed that in my system the "Web Content" asset type has **NOT** been moved to the second section of the page. (see image below).
![image](https://cloud.githubusercontent.com/assets/4906504/9757330/3493fb32-56e0-11e5-9147-f8dcfa0f1928.png)

Indeed, every customized structure defaults to the _Basic Web Content_ workflow configuration, meaning that the liferay-webcontent-workflow-portlet does not work in my environment.

Any idea how to solve that?

Thank you very much.

**Comment by timtelcik** [comment] 2015-09-09 09:45
Hello Michele,

Thank you for reporting this issue to Permeance Liferay Marketplace Support. 

I understand the web content workflow portlet is not behaving as expected. 

To help us investigate, can you please advise the following : 

1/ Did you download the web content workflow portlet from Sourceforge or the Liferay Marketplace ?

2/ How did you deploy the workflow portlet ?

Also, please attach the portal log(s) which show the deployment of the web content workflow portlet.

Regards,

Tim

**Comment by micheledallatorre** [comment] 2015-09-09 15:56
Hello @timtelcik,
Thank you very much for your answer!

My answers below.
1. Liferay Marketplace
2. We put the workflow portlet in the Liferay _deployments_ folder, using auto-deploy Liferay feature
3. Which logs do you need exactly?

Thanks,
Michele

**Comment by timtelcik** [comment] 2015-09-10 01:52
Hello Michele,

we may have found the cause of the issue you are observing.

We observed if you install the Web Content Workflow portlet before installing the Kaleo EE Workflow plugin, the "Web Content" asset type is not registered as expected.

However, if you install the Web Content Workflow portlet after installing the Kaleo EE Workflow plugin, the "Web Content" asset type is registered as expected.

Hence, there is an undocumented installation dependency between the  Web Content Workflow portlet and  Kaleo EE Workflow plugin.

Another way to the confirm the installation, is review the Control Panel items.

You should also see the following items in the Control Panel for a valid installation:
- Workflow Configuration
- Web Content Workflow Configuration (new item)

Please review your local installation process and advise the outcome.

Thanks

Tim

**Comment by micheledallatorre** [comment] 2015-09-10 10:40
Hi Tim,
I do not know if the Web Content Workflow portlet was installed before the Kaleo EE Workflow plugin, since this was done a long time ago...

However, I do have the following 2 items in my Control Panel:
![image](https://cloud.githubusercontent.com/assets/4906504/9786268/0f4d5ab0-57b9-11e5-8929-f28f935e1939.png)

How would you suggest to proceed?

**Comment by timtelcik** [comment] 2015-09-12 14:21
Hello Michele,

I understand you are not aware of the previous installation process for the Web Content Workflow portlet.

If the issue you are observing is related to installation order, you may try re-installing 
the Web Content Workflow portlet.

This may resolve the issue and is worth trying.

I would also like to query your current Liferay Portal 6.1 EE GA3 runtime environment. 

Are you hosting Liferay Portal with Apache Tomcat or another servlet container or application server ?

Testing on our was conducted with the Liferay Portal 6.1 EE GA3 + Apache Tomcat bundle.

Regarding the portal logs, please review the servlet container log (eg. Apache Tomcat catalina.out log file) 
and the Liferay Portal log file.

Please review and advise.

Regards,

Tim

**Comment by micheledallatorre** [comment] 2015-09-15 07:52
Hi Tim!

I am hosting Liferay Portal + JBoss bundle.

Re your piece of advice about re-installing the Web Content Workflow portlet, do you believe this could create issues?
E.g. I am scared I would not be able to approve any web content if the re-installation goes wrong...
What do you reckon?

Re the logs I do not see anything strange, I can attach the logs if you need them.

Thanks,
Michele

**Comment by cwho** [comment] 2015-09-17 12:04
Hi Michele,

Sorry for the delay.

Please try reinstalling the portlet. It should not cause any issues about approving web content.

Please attach the logs (around startup or installing the portlet) please. There is a JBoss known issue with the portlet that causes it not to work (the portlet is started before Liferay or Kaleo and fails to integrate with them). If it is the known issue, we'll be able post a fix in the coming week.

Cheers,
Chun

**Comment by micheledallatorre** [comment] 2015-09-18 09:38
Hello,
attached the logs (filtered to show only info about the portlet) upon restarting the server.

I will report with more info when I'll try to reinstal the portlet.

**liferay log**

```
09:33:28,152 INFO  [MSC service thread 1-3][HotDeployImpl:185] Deploying webcontent-workflow-portlet from queue
09:33:28,152 INFO  [MSC service thread 1-3][PluginPackageUtil:1049] Reading plugin package for webcontent-workflow-portlet
09:33:28,277 INFO  [MSC service thread 1-3][PortletHotDeployListener:295] Registering portlets for webcontent-workflow-portlet
09:33:28,386 INFO  [MSC service thread 1-3][PortletHotDeployListener:454] 1 portlet for webcontent-workflow-portlet is available for use
```

**server.log**

```
    Line 3202: 09:03:00,784 INFO  [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) JBAS015003: Found webcontent-workflow-portlet.war in deployment directory. To trigger deployment create a file called webcontent-workflow-portlet.war.dodeploy
    Line 3227: 09:03:01,439 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-3) JBAS015876: Starting deployment of "webcontent-workflow-portlet.war"
    Line 3228: 09:08:01,637 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 2) JBAS015870: Deploy of deployment "webcontent-workflow-portlet.war" was rolled back with failure message Operation cancelled
    Line 3293: 09:16:55,541 INFO  [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) JBAS015003: Found webcontent-workflow-portlet.war in deployment directory. To trigger deployment create a file called webcontent-workflow-portlet.war.dodeploy
    Line 3318: 09:16:58,365 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) JBAS015876: Starting deployment of "webcontent-workflow-portlet.war"
    Line 3324: 09:21:56,925 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 2) JBAS015870: Deploy of deployment "webcontent-workflow-portlet.war" was rolled back with failure message Operation cancelled
    Line 3371: 09:25:34,078 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) JBAS015877: Stopped deployment webcontent-workflow-portlet.war in 14784ms
    Line 3410: 09:29:34,774 INFO  [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) JBAS015003: Found webcontent-workflow-portlet.war in deployment directory. To trigger deployment create a file called webcontent-workflow-portlet.war.dodeploy
    Line 3434: 09:29:38,331 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) JBAS015876: Starting deployment of "webcontent-workflow-portlet.war"
    Line 3446: 09:30:23,933 INFO  [javax.enterprise.resource.webcontainer.jsf.config] (MSC service thread 1-1) Initializing Mojarra 2.1.7-jbossorg-1 (20120227-1401) for context '/webcontent-workflow-portlet'
    Line 3447: 09:30:23,996 INFO  [au.com.permeance.liferay.util.startup.StartupListener] (MSC service thread 1-1) Starting up Web Content Workflow Configuration Portlet
    Line 3448: 09:30:23,996 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/webcontent-workflow-portlet]] (MSC service thread 1-1) StandardWrapper.Throwable: java.lang.NullPointerException
    Line 3449:  at com.liferay.portal.kernel.workflow.WorkflowHandlerRegistryUtil.getWorkflowHandler(WorkflowHandlerRegistryUtil.java:46) [portal-service.jar:]
    Line 3463: 09:30:24,011 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/webcontent-workflow-portlet]] (MSC service thread 1-1) Servlet /webcontent-workflow-portlet threw load() exception: java.lang.NullPointerException
    Line 3464:  at com.liferay.portal.kernel.workflow.WorkflowHandlerRegistryUtil.getWorkflowHandler(WorkflowHandlerRegistryUtil.java:46) [portal-service.jar:]
    Line 3478: 09:30:24,011 INFO  [org.jboss.web] (MSC service thread 1-1) JBAS018210: Registering web context: /webcontent-workflow-portlet
    Line 3672: 09:33:28,152 INFO  [stdout] (MSC service thread 1-3) 09:33:28,152 INFO  [MSC service thread 1-3][HotDeployImpl:185] Deploying webcontent-workflow-portlet from queue
    Line 3674: 09:33:28,152 INFO  [stdout] (MSC service thread 1-3) 09:33:28,152 INFO  [MSC service thread 1-3][PluginPackageUtil:1049] Reading plugin package for webcontent-workflow-portlet
    Line 3676: 09:33:28,230 INFO  [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/webcontent-workflow-portlet]] (MSC service thread 1-3) Initializing Spring root WebApplicationContext
    Line 3677: 09:33:28,277 INFO  [stdout] (MSC service thread 1-3) 09:33:28,277 INFO  [MSC service thread 1-3][PortletHotDeployListener:295] Registering portlets for webcontent-workflow-portlet
    Line 3679: 09:33:28,386 INFO  [stdout] (MSC service thread 1-3) 09:33:28,386 INFO  [MSC service thread 1-3][PortletHotDeployListener:454] 1 portlet for webcontent-workflow-portlet is available for use
    Line 4042: 09:33:55,948 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 2) JBAS018559: Deployed "webcontent-workflow-portlet.war"
```

Thanks,
Michele

**Comment by cwho** [comment] 2015-09-18 12:51
Hi Michele,

Thanks - let me know how the re-install goes. 

Meanwhile I have another workaround for you to try too, which involves editing two files on the deployed "webcontent-workflow-portlet.war" directory. On the Liferay 6.1 JBoss bundle, they are in:
\liferay-portal-6.1-ee-ga3-sp4\jboss-7.1.1\standalone\deployments\webcontent-workflow-portlet.war\WEB-INF

(1) in file
\liferay-portal-6.1-ee-ga3-sp4\jboss-7.1.1\standalone\deployments\webcontent-workflow-portlet.war\WEB-INF\web.xml
, edit the following block :

```
      <servlet>
        <servlet-name>Startup</servlet-name>
        <servlet-class>au.com.permeance.liferay.util.startup.StartupServlet</servlet-class>
        <load-on-startup>0</load-on-startup>
    </servlet>
```

to (i.e. commenting it out):

```
<!--    <servlet>
        <servlet-name>Startup</servlet-name>
        <servlet-class>au.com.permeance.liferay.util.startup.StartupServlet</servlet-class>
        <load-on-startup>0</load-on-startup>
    </servlet> -->
```

(2) if you also have kaleo-web.war in the deployment area, then in file:
\liferay-portal-6.1-ee-ga3-sp4\jboss-7.1.1\standalone\deployments\webcontent-workflow-portlet.war\WEB-INF\liferay-plugin-package.properties
add:

```
required-deployment-contexts=kaleo-web
```

to the bottom of the file.

This should stop the webcontent-workflow-portlet from prematurely initializing before liferay/kaleo is initialized.

Do let us know how you go with these changes.

Cheers,
Chun

**Comment by cwho** [comment] 2015-09-23 00:40
H Michele,

Do you have any updates on how reinstalling the plugin, or the workarounds that I have specified here, is working for you?

Cheers,
Chun

**Comment by micheledallatorre** [comment] 2015-09-23 15:06
@cwho Thank you very much for your help.

I tried the workaround you suggested in https://github.com/permeance/liferay-webcontent-workflow-portlet/issues/6#issuecomment-141443411, and so far everything has been working correctly! :+1: 

I will keep you posted if I reinstall the portlet, or if I discover other issues.

Thank you,
Michele

**Comment by cwho** [comment] 2015-09-23 23:49
Thanks Michele!

My sincere apologies for the troubles you had with the plugin, we will hopefully be able to release a new version soon that incorporates these fixes for when running on JBoss.

I'll close this thread now, feel free to reopen or raise a new one if you find any other issues with the plugin.

Cheers,
Chun

**Closed as completed by cwho** 2015-09-23 23:49 UTC

**Comment by micheledallatorre** [comment] 2015-09-24 07:03
Cheers!
Michele
